app = "cloud-culture"   # <-- pick a globally-unique name and keep it consistent
primary_region = "lax"      # you're on Pacific time; "lax" is usually closest

[build]
  # Using the Dockerfile at repo root

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "3s"
  interval = "10s"
  method = "GET"
  path = "/"
  timeout = "2s"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
